<?php /* application/views/scripts/users/edit.phtml */ ?>
 
<h1>Edição de Dispositivo</h1>
 
<p>
<a href="<?php echo $this->url(array(
    'controller' => 'device',
    'action'     => 'list')); ?>" title="Listar Dispositivos">Lista de Dispositivos</a>
</p>
 
<?php if ( isset($this->message) ) echo $this->message; ?>
 
<?php if ( isset($this->form) ) : ?>
    <?php echo $this->form; ?>
<?php endif; ?>