<?php /* application/views/scripts/users/list.phtml */ ?>
 
<h1>Lista de Serviço</h1>
 
<p>
<a href="<?php echo $this->url(array(
    'controller' => 'service',
    'action'     => 'create')); ?>" title="Novo Serviço">Incluir novo serviço</a>
</p>
 
<table cellspacing="1" cellpadding="1" border="1" width="500">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Classificação</th> 
            <th>Descrição</th>
            <th>Ocorrências</th>
            <th>Status</th>
        </tr>
     </thead>
     <tbody>
        <?php foreach ( $this->services as $service ) : ?>
            <tr>
                <td><?php echo $service->service_id; ?></td>           
                <td><?php echo $this->escape($service->service_name); ?></td>
                <td><?php echo $this->escape($service->service_type); ?></td>
                <td><?php echo $this->escape($service->description); ?></td>  
                <td><?php echo $this->escape($service->qtd_cases); ?></td>  
                <td><?php echo $this->escape($service->status); ?></td>
                <td>
                   <a href=<?php echo "service/update/service_id/$service->service_id" ?> >Editar</a>
                </td>
                <td>
                   <a href=<?php echo "service/remove/service_id/$service->service_id" ?> >Ecluir</a>
                </td>                
            </tr>
        <?php endforeach; ?>
     </tbody>
</table>

<p>
<a href="<?php echo $this->url(array(
    'controller' => 'service',
    'action'     => 'create')); ?>" title="Novo Serviço">Incluir novo serviço</a>
</p>