<html>
    <head>
        <base href="<?php echo $this->serverUrl() . $this->baseUrl() ?>/" />
        <?php echo $this->headTitle('Opa!!!') ?>
        <?php
        // $this->headScript()->appendFile('algum_javascript.js');
        $this->headLink()->prependStylesheet('css/opa.css');
        $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                ->appendHttpEquiv('Content-Language', 'pt_BR');

        echo $this->headMeta();
        echo $this->headScript();
        echo $this->headLink();
        ?>

        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <style type="text/css">
            html { height: 100% }
            body { height: 100%; margin: 0; padding: 0 }
            #map_canvas { height: 100% }
        </style>
        <script type="text/javascript"
                src="http://maps.googleapis.com/maps/api/js?sensor=true&language=pt_BR">
        </script>
        <script type="text/javascript">
            var geocoder;
            var map;
            var infowindow = new google.maps.InfoWindow();
            var marker;
            
            function initialize() {
                geocoder = new google.maps.Geocoder();
                var latlng = new google.maps.LatLng(<?php echo $this->occurrence['latitude'] . ','. $this->occurrence['longitude'];?>);

                var myOptions = {
                    zoom: 16,
                    center: latlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                }
                map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
                marker = new google.maps.Marker({
                    position: latlng, 
                    map: map, 
                    title:"Local aproximado da solicitação"
                });   
            }
            
            function detectBrowser() {
                var useragent = navigator.userAgent;
                var mapdiv = document.getElementById("map_canvas");
    
                if (useragent.indexOf('iPhone') != -1 || useragent.indexOf('Android') != -1 ) {
                    mapdiv.style.width = '70%';
                    mapdiv.style.height = '50%';
                } else {
                    mapdiv.style.width = '600px';
                    mapdiv.style.height = '800px';
                }
            }           

            function codeLatLng() {
                var input = document.getElementById("latlng").value;
                var latlngStr = input.split(",",2);
                var lat = parseFloat(latlngStr[0]);
                var lng = parseFloat(latlngStr[1]);
                var latlng = new google.maps.LatLng(lat, lng);
                geocoder.geocode({'latLng': latlng}, function(results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        if (results[1]) {
                            map.setZoom(11);
                            marker = new google.maps.Marker({
                                position: latlng,
                                map: map
                            });
                            infowindow.setContent(results[1].formatted_address);
                            infowindow.open(map, marker);
                        }
                    } else {
                        alert("Geocoder failed due to: " + status);
                    }
                });
            }    
        </script>        


    </head>
    <body onload="initialize()">
        <div id="header">
            <div id="logo">
                <img src="images/opa.gif" />
            </div>
        </div>
        <div id="content">
            <?php echo $this->layout()->content ?>
 
        </div>
        <div id="map_canvas" style="width:90%; height:75%"></div>     
        <div id="footer">
            <p>
                Leia <a href="http://framework.zend.com/">
                    nossos termos e condições de uso</a>. 
            </p>
        </div>
       
    </body>
</html>